name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: setup Go
        run: 'sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y golang-1.23'

      - name: run tests
        run: '/usr/lib/go-1.23/bin/go test -count=1 ./...'
